server:
  port: 0
spring:
  application:
    name: DeliveryManager
  activemq:
    broker-url: tcp://localhost:61616
  security:
    user:
      name: synxt
      password: Open123$
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: SYSTEM
    password: Oracle@123
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     '[hibernate.format_sql]': true
     '[generate_statistics]': true
logging:
  level:
    '[org.hibernate.type]': trace
    '[org.hibernate.stat]': debug
    '[org.springframework.security.web.FilterChainProxy]': debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true
